site_name: Foundry
nav:
  - Project Overview:
      - About: about.md
      - IO: io.md
  - Governance:
      - Agents: agents.md
  - Contributing:
      - Overview: contributing.md
      - Branch Naming: contributing/branching.md
